### ISSUE TITLE
Navbar logo references @githinode/hinode/static/img, not assets/img

### ISSUE THREAD

**Issue by lorenzosama** [gethinode/child#90]
https://github.com/gethinode/child/blob/36a1f0d8d553d0b93d62b22b47354d35536ff13a/config/_default/params.toml#L17

While editing this config I realized it will only point to the static/img folder in my node_modules dependencies. Referencing images I place in assets/img is never successful. Instead of the image I expect I will get the word "logo" after my blog's name. Currently I'm not using the logo parameter at all to mitigate this.

I'm learning how hinode works so I'm not 100% sure what the issue is but I think it's related to this line
https://github.com/gethinode/hinode/blob/d3a15b5b1e5f62577a07e28015b48bcddbc40ef2/layouts/shortcodes/navbar.html#L76
. We are getting the logo's url without creating a link referencing the url dictionary as seen on this line
https://github.com/gethinode/hinode/blob/f6aeed969c4e1f67f52f909edf4590d6d90ca92d/layouts/partials/home/featured.html#L13

Thank you and sorry if I am misunderstanding how to use the navigation logo parm

**Comment by markdumay** [comment]
As your logo is presumably a vector image, the file is expected to be present in your local `static/img` folder. I'll update the [documentation for the navbar](https://gethinode.com/docs/0.9/configuration/navigation/) in a next release.

For future reference, would you mind [submitting new issues/feature requests to the main repository](https://github.com/gethinode/hinode/issues) instead?

**Comment by lorenzosama** [comment]
Thank you for the quick response and sorry about submitting in the wrong repo. 🙇
